apiVersion: v1
description: This is a template to run a high available memcached instance.
engine: gotpl
home: https://memcached.org
icon: https://cdn.iconscout.com/public/images/icon/free/png-256/memcached-company-brand-logo-30dd33911b1dc26b-256x256.png
keywords:
- jamf
- JamfPro
- Managed Service
- Memcached
- Data Quest AG
maintainers:
- name: Fabian Hartmann
  email: fhartmann@dataquest.ch
name: memcached
#kubeVersion:
sources:
- https://github.com/memcached/memcached
version: 1.0.5
appVersion: 1.5.9
deprecated: false
