.catalog:
  name: "GlusterFS"
  version: "5-lnb1"
  description: "Gluster FS (3x) replicated volume"
  uuid: glusterfs-0
  questions:
    - variable: "VOLUME_NAME"
      description: "Name to give the Gluster volume"
      label: "Volume Name"
      required: true
      default: "vol"
      type: "string"
glusterfs-server:
  metadata:
    volume_name: "${VOLUME_NAME}"
  storage_driver:
    name: rancher-gluster
    scope: environment
    volume_access_mode: multiHostRW
