name: "MM-ASUS"
description: |
  MacManagement Apple Software Update Service based on Reposado and Margarita.
version: 1.0.0
category: "Client Management"
maintainer: Fabian Hartmann
projectURL: https://github.com/MM-MacManagement/MM-REPOSADO
