apiVersion: v1
description: This is a template to run a high available memcached instance.
engine: gotpl
home: https://memcached.org
icon: https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Memcached.svg/200px-Memcached.svg.png
keywords:
- jamf
- JamfPro
- Managed Service
- Memcached
- Data Quest AG
maintainers:
- name: Fabian Hartmann
  email: fhartmann@dataquest.ch
name: memcached
#kubeVersion:
sources:
- https://github.com/memcached/memcached
version: 2.0.1
appVersion: 1.5.10
deprecated: false
