version: '2'
catalog:
  name: "Rattic Password DB"
  version: 1.0.0
  description: "Store your passwords in a DB"
  #minimum_rancher_version:
  #maximum_rancher_version:
  #upgrade_from:
  questions:
    - variable: "RC_DEBUG"
      label: "Enable Debug Mode"
      description: |  # The description of the question to show the user how to answer the question.
      default: false
      required: true
      type: boolean
    - variable: "RC_LOGLEVEL"
      label: "Define Log Level"
      description: | # The description of the question to show the user how to answer the question.
      default: "ERROR"
      required: false
      type: string
    - variable: "RC_SECRET"
      label: "Database Encryption Key"
      description: | # The description of the question to show the user how to answer the question.
      default: ""
      required: true
      type: password
    - variable: "RC_TC"
      label: "Enter your Timezone"
      description: | # The description of the question to show the user how to answer the question.
      default: "Europe/Zurich"
      required: true
      type: enum
      options: # List of options if using type of `enum`
        - Europe/Paris
        - Europe/Berlin
    - variable: "RC_PWEXP"
      label: "USer Password valit for"
      description: | # Test
      default: 90
      required: true
      type: int
    - variable: "RC_PWEXPORT"
      label: "Allow export to file"
      description: | # Allows the export of all PWs to a file.
      default: false
      required: true
      type: boolean
    - variable: RC_ATTSIZE
      label: "Size of attachments"
      description: | # Test
      default: 16777216
      required: yes
      type: int
    - variable: "RC_DB_NAME"
      label: "Database name"
      description: Name ot the Database.
      default: ratticDB
      required: true
      type: string
    - variable: "RC_DB_USER"
      label: "Database User"
      description: User ot the Database.
      default: ratticUser
      required: true
      type: string
    - variable: "RC_DB_PW"
      label: "Database User password"
      description: Password ot the Database User.
      default: ""
      required: true
      type: password
    - variable: "RC_DB_PORT"
      label: "Database Port"
      description: Port of the Database.
      default: 3306
      required: true
      type: int
    - variable: "RC_MAIL"
      label: "Mail Service"
      description: | #
      default: false
      required: true
      type: boolean
    - variable: "RC_MAIL_FP"
      label: "Mail FP"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_MAIL_HOST"
      label: "Mailserver"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_MAIL_PORT"
      label: "Mailserver Port"
      description: | #
      default: ""
      required: false
      type: int
    - variable: "RC_MAIL_TLS"
      label: "Mailserver  uses TLS"
      description: | #
      default: false
      required: false
      type: boolean
    - variable: "RC_MAIL_USER"
      label: "Mailserver User"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_MAIL_PW"
      label: "Mailserver User Password"
      description: | #
      default: ""
      required: false
      type: password
    - variable: "RC_MAIL_FROM"
      label: "Mail Sender"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP"
      label: "Enable LDAP Bind"
      description: | #
      default: false
      required: true
      type: boolean
    - variable: "RC_LDAP_URI"
      label: "Path to LDAP Server"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP_BINDN"
      label: "LDAP bind DN"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP_BINDPW"
      label: "LDAP bind PW"
      description: | #
      default: ""
      required: false
      type: password
    - variable: "RC_LDAP_REQCERT"
      label: "LDAP Requires certificate"
      description: | #
      default: false
      required: false
      type: boolean
    - variable: "RC_LDAP_REF"
      label: "RC_LDAP_REF"
      description: | #
      default: false
      required: false
      type: boolean
    - variable: "RC_LDAP_TLS"
      label: "LDAP TLS"
      description: | #
      default: false
      required: false
      type: boolean
    - variable: "RC_LDAP_USERBASE"
      label: "LDAP User Base DN"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP_USERFILTER"
      label: "LDAP User Filter"
      description: | #
      default: "(uid=%(user)s)"
      required: false
      type: string
    - variable: "RC_LDAP_GROUPBASE"
      label: "LDAP Group Base DN"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP_GROUPFILTER"
      label: "LDAP Group Filter"
      description: | #
      default: "(objectClass=groupOfNames)"
      required: false
      type: string
    - variable: "RC_LDAP_GROUPTYPE"
      label: "LDAP Group Type"
      description: | #
      default: "GroupOfNamesType"
      required: false
      type: string
    - variable: "RC_LDAP_STAFF"
      label: "LDAP STAFF"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_LDAP_ALLOWPWCHANGE"
      label: "LDAP allow Password change"
      description: | #
      default: true
      required: false
      type: boolean
    - variable: "RC_LDAP_ALLOWEDHOST"
      label: "LDAP allowed Hosts"
      description: | #
      default: "[‘ratticdbhost',]"
      required: false
      type: string
    - variable: "RC_BU"
      label: "Enable Backup"
      description: | #
      default: false
      required: true
      type: boolean
    - variable: "RC_BUGPG"
      label: "Backup PGP Keys"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_BUREC"
      label: "RC_BUREC"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "RC_BUDIR"
      label: "Backup Destination"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "WS_DOMAIN"
      label: "WS_DOMAIN"
      description: | #
      default: ""
      required: false
      type: string
    - variable: "WS_PORT"
      label: "WS_PORT"
      description: | #
      default: ""
      required: false
      type: int
