version: '2'
catalog:
  name: "Rattic Password DB"
  version: 1.0.0
  description: "Store your passwords in a DB"
  #minimum_rancher_version:
  #maximum_rancher_version:
  #upgrade_from:
  questions:
    - variable: "RC_DEBUG"
      label: "Enable Debug Mode"
      description: |  # The description of the question to show the user how to answer the question.
      default: false
      required: true
      type: boolean
    - variable: "RC_LOGLEVEL"
      label: "Define Log Level"
      description: | # The description of the question to show the user how to answer the question.
      default: "ERROR"
      required: false
      type: string
    - variable: "RC_SECRET"
      label: "Database Encryption Key"
      description: | # The description of the question to show the user how to answer the question.
      default: ""
      required: true
      type: password
    - variable: "RC_TC"
      label: "Enter your Timezone"
      description: | # The description of the question to show the user how to answer the question.
      default: "Europe/Zurich"
      required: true
      type: enum
      options: # List of options if using type of `enum`
        - Europe/Paris
        - Europe/Berlin
    - variable: "RC_PWEXP"
      label: "USer Password valit for"
      description: | # Test
      default: false
      required: true
      type: boolean
    - variable: "RC_PWEXPORT"
      label: "Allow export to file"
      description: | # Allows the export of all PWs to a file.
      default: false
      required: true
      type: boolean
    - variable: "RC_ATTSIZE"
      label: "Define attachment file size"
      description: | Size of an attachment.
      default: "16777216"
      required: false
      type: int
    - variable: "RC_DB_NAME"
      label: "Database name"
      description: Name ot the Database.
      default: ratticDB
      required: true
      type: string
    - variable: "RC_DB_USER"
      label: "Database User"
      description: User ot the Database.
      default: ratticUser
      required: true
      type: string
    - variable: "RC_DB_PW"
      label: "Database User password"
      description: Password ot the Database User.
      default: ratticDB
      required: true
      type: password
