.catalog:
  name: "MM-ASUS"
  version: "1.0.0"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "baseurl"
      description: |
        Basis URL der Services.
      label: "Basis URL"
      required: true
      type: string
      default: "example.com"
