version: '2'
services:
  manager:
    image: fabianhartmann/mm-reposado:develop
    environment:
      VIRTUAL_HOST: ${margaritaurl}
      MODE: "MANAGER"
      AUTODISABLEDEPRECATED: ${autodisabledeprecated}
      PURGEDEPRECATED: ${autoremovedeprecated}
      AUTOSECURITYUPDATES: ${autosecurityupdates}
      AUTOUPDATEPATTERNS: ${updatetypes}
    stdin_open: true
    volumes:
    - /srv/MMServiceData/MM-REPOSADO:/srv/MMServiceData/MM-REPOSADO
    tty: true
    labels:
      io.rancher.container.pull_image: always
      addtolb: 'true'
  setup:
    image: fabianhartmann/mm-setup:develop
    environment:
      GITREPO: ${gitsetupsource}
    volumes:
    - /srv/MMServiceData:/srv/MMServiceData
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  asus:
    image: fabianhartmann/mm-reposado:develop
    environment:
      VIRTUAL_HOST: ${reposadourl}
      MODE: "REPO"
    stdin_open: true
    volumes:
    - /srv/MMServiceData/MM-REPOSADO:/srv/MMServiceData/MM-REPOSADO
    tty: true
    labels:
      io.rancher.container.pull_image: always
      addtolb: 'true'
