version: '2'
catalog:
  name: "Rattic Password DB"
  version: 1.0.0
  description: "Store your passwords in a DB"
  #minimum_rancher_version:
  #maximum_rancher_version:
  #upgrade_from:
  questions:
    - variable: "RC_DEBUG"
      label: "Enable debug Mode?"
      description: |
      default: false
      required: true
      type: boolean
