
## nextcloud image repository
image: "nextcloud"
## nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
imageTag: "14.0.3-fpm-alpine"

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:

## Specify imagePullSecrets
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
##
# imagePullSecrets: myregistrykey

## Number of replicas to create
replicas: 3

## Pod disruption budget minAvailable count
## Ensure this value is lower than replicaCount in order to allow a worker
## node to drain successfully
pdbMinAvailable: 1
web:
  image: "nginx"
  imageTag: "1.15-alpine"

db:
  name: nextclouddb
  port: 3306
  user: ncuser
  image: "mysql/mysql-server"
  imageTag: "5.7.23"
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  settings:
    logconsole: true
  logs:
    ## Expose jamfpro logs
    enabled: true
    ## baseimage for log container
    image: "busybox"
    imageTag: "1.29.2"
    logfiles:
      - name: mysqld
        path: "/var/log/mysqld.log"

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 100m

service:
  type: ClusterIP
  port: 11211
  externalIPs: []

metrics:
  ## Expose nextcloud metrics in Prometheus format
  enabled: false

  ## nextcloud exporter image and tag
  image: quay.io/prometheus/nextcloud-exporter:v0.4.1

  ## Specify a imagePullPolicy
  ## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  # imagePullPolicy: IfNotPresent

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}

## Customer number from DQ Tool
custnr: "0000"

## Custom Servicename
customservicename:
  enabled: false
  name:
## UID ot the instance
instanceid: "4E4888E3-E03D-4489-85F6-8211F90303AD"
## Node labels and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
nodeSelector: {}
tolerations: []
affinity: {}
