# Default values for sal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: macadmins/sal
  tag: 3.0.3
  pullPolicy: IfNotPresent

database:
  port: 5432

service:
  name: http
  containerPort: 8000
  protocol: TCP

ingress:
  enabled: true
  annotations: {}
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  hosts:
    - sal.dq.solutions
