apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sal.fullname" . }}
  labels:
    app: {{ template "sal.name" . }}
    chart: {{ template "sal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sal.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sal.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: ADMIN_PASS
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: DB_PASS
          - name: DB_PORT_5432_TCP_ADDR
            value: {{ .Values.database.port }}
          - name: DB_PORT_5432_TCP_PORT
            value: {{ .Values.database.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
