apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "sal.fullname" . }}
  labels:
    app: {{ template "sal.name" . }}
    chart: {{ template "sal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "sal.name" . }}
      release: {{ .Release.Name }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ template "sal.name" . }}
        release: {{ .Release.Name }}
        tier: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.containerPort }}
              protocol: {{ .Values.service.protocol }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: ADMIN_PASS
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: DB_PASS
          - name: DB_PORT_5432_TCP_ADDR
            value: {{ .Values.database.port }}
          - name: DB_PORT_5432_TCP_PORT
            value: {{ .Values.database.port }}
