.catalog:
  name: "MM-ASUS"
  version: "1.0.3"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "baseurl"
      description: |
        Basis URL der Services.
      label: "Basis URL"
      required: true
      type: string
      default: "example.com"
    - variable: "httpport"
      description: |
        Exposed Port for HTTP.
      label: "HTTP Port"
      required: true
      type: int
      default: 80
    - variable: "httpsport"
      description: |
        Exposed Port for TLS.
      label: "HTTPS Port"
      required: true
      type: int
      default: 443
    - variable: "gitsetupsource"
      description: |
        URL to a GIT-Repo to setup the Service.
      label: "GIT Source"
      required: true
      type: string
      default: "https://github.com/MM-MacManagement/WebTemplates/archive/axonlab.tar.gz"
    - variable: "restorefrombackup"
      description: |
        If you want to restore this Service from a Backup,
        choose true and select the restore type.
      label: "Restore from Backup"
      required: true
      type: boolean
      default: false
    - variable: "restoretype"
      description: |
      label: "Restore Mechanism"
      required: false
      type: enum
      options:
        - FTP
        - SMB
        - HTTP
        - VOLUME
    - variable: "restoreconfig"
      description: |
        Enter a valid Configuration for the choosen restore mechanism.
      label: "Restore Config"
      required: false
      type: multiline
      default: |
        serverpath=
        user=
        password=
    - variable: "autodisabledeprecated"
      description: |
        Disable Updates in every branche flaged as deprecated.
      label: "Audo disable deprecated Updates"
      required: true
      type: boolean
      default: true
    - variable: "autosecurityupdates"
      description: |
        Set to True will enable Updates found by Auto add Patterns to all branches automatically.
      label: "Automatic Update"
      required: true
      type: boolean
      default: true
    - variable: "updatetypes"
      description: |
        Enter Grep pattern to identifie Updates that schould be added to all branches automatically.
      label: "Auto add Patterns"
      required: true
      type: string
      default: "XProtect\\|Core Suggestions Configuration Data\\|MRT Configuration Data\\|Gatekeeper Configuration Data\\|Incompatible Kernel Extension Configuration Data\\|System Integrity Protection Configuration Data\\|Security Update"
LB:
  lb_config:
    certs: []
    port_rules:
    - hostname: masus.praxisservices.ch
      priority: 1
      protocol: http
      service: manager
      source_port: ${httpport}
      target_port: 8089
    - hostname: asus.praxisservices.ch
      priority: 2
      protocol: http
      service: asus
      source_port: ${httpport}
      target_port: 8088
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
