version: '2'
services:
  manager:
    scale: 1
    start_on_create: true
  LB:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: masus.praxisservices.ch
        priority: 1
        protocol: http
        service: manager
        source_port: 80
        target_port: 8089
      - hostname: asus.praxisservices.ch
        priority: 2
        protocol: http
        service: ASUS
        source_port: 80
        target_port: 8088
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  setup:
    scale: 1
    start_on_create: true
  ASUS:
    scale: 1
    start_on_create: true
