apiVersion: v1
kind: Service
metadata:
  labels:
    dqservice: hostedmemcached
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "memcached.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None  # Headless service
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: "{{ template "memcached.fullname" . }}"
    dqservice: hostedmemcached
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
