# config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jamfpro.fullname" . }}-hostingconfig
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  db.name: "{{ .Values.db.name }}"
  db.port: "{{ .Values.db.port }}"
  cache.enabled: "{{ .Values.jamfpro.cacheenabled }}"
{{- if .Values.jamfpro.cacheenabled }}
  cache.memcachedservice: jamf-memcached-srv
  cache.uniqueid: {{ default uuidv4 }}
{{- end -}}
