---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jamfpro.fullname" . }}-mysqlconfig
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  mysql-config: |
    # For advice on how to change settings please see
    # http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html

    [mysqld]
    #
    # Remove leading # and set to the amount of RAM for the most important data
    # cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
    # innodb_buffer_pool_size = 128M
    #
    # Remove leading # to turn on a very important data integrity option: logging
    # changes to the binary log between backups.
    # log_bin
    #
    # Remove leading # to set options mainly useful for reporting servers.
    # The server defaults are faster for transactions and fast SELECTs.
    # Adjust sizes as needed, experiment to find the optimal values.
    # join_buffer_size = 128M
    # sort_buffer_size = 2M
    # read_rnd_buffer_size = 2M
    connect_timeout=100000
    wait_timeout=100000
    interactive_timeout=100000
    innodb_buffer_pool_size=2000M
    innodb_file_per_table=1
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/lib/mysql/mysql.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql

    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0

    #log-error=/var/log/mysqld.log
    pid-file=/var/run/mysqld/mysqld.pid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jamfpro.fullname" . }}-hostingconfig
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  db.name: "{{ .Values.db.name }}"
  db.port: "{{ .Values.db.port }}"
  cache.enabled: "{{ .Values.jamfpro.cacheenabled }}"
{{- if .Values.jamfpro.cacheenabled }}
  cache.memcachedservice: jamf-memcached-srv
  cache.uniqueid: {{ default uuidv4 }}
{{- end -}}
