apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jamfpro.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/add-base-url: "true"
    #nginx.ingress.kubernetes.io/app-root: /
    # Force redirects to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Configure some TLS Ciphers
    nginx.ingress.kubernetes.io/ssl-ciphers: "RC4:HIGH:!MEDIUM:!aNULL:!MD5:!DH:!EDH"
    #nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"
    # HA Routing configuration
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: haroute
    # Disable NGINX version
    nginx.org/server-tokens: "false"
    #nginx.org/client-max-body-size: "0"
    #nginx.ingress.kubernetes.io/client-max-body-size: "0"
    # Set client body size to unlimited, this is nessesary to make pkg uploads possible.
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Port, X-Forwarded-Prefix"
    #nginx.ingress.kubernetes.io/upstream-hash-by: "$request_uri"
    #nginx.ingress.kubernetes.io/proxy-redirect-from: "test"
    #nginx.ingress.kubernetes.io/proxy-redirect-to: "/"
spec:
  tls:
  - hosts:
    - {{ template "jamfpro.fullname" . }}.dq.solutions
    secretName: jamf-webcert
{{- if .Values.jamfpro.customdomain.enabled}}
  - hosts:
    - {{ .Values.jamfpro.customdomain.fqdn }}
    secretName: {{ template "jamfpro.fullname" . }}-customcert-{{ .Values.jamfpro.customdomain.fqdn }}
{{- end }}
  rules:
  - host: {{ template "jamfpro.fullname" . }}.dq.solutions
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "jamfpro.fullname" . }}-jamfwebapp-srv
          servicePort: 80
{{- if .Values.jamfpro.customdomain.enabled}}
  - host: {{ .Values.jamfpro.customdomain.fqdn }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "jamfpro.fullname" . }}-jamfwebapp-srv
          servicePort: 80
{{- end }}
# https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#rewrite
# https://www.ssllabs.com/ssltest/analyze.html?d=jamf.dq.solutions
