apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "jamfpro.fullname" . }}-dbcredentials
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  db.user: {{ randAlphaNum 10 | b64enc | quote }}
  db.userpw: {{ randAlphaNum 25 | b64enc | quote }}
  db.rootpw: {{ randAlphaNum 25 | b64enc | quote }}
# echo -n 'PLAINTEXTPW' | base64
# https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
{{- if .Values.jamfpro.customdomain.enabled}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "jamfpro.fullname" . }}-customcert-{{ .Values.jamfpro.customdomain.fqdn }}
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
data:
  tls.crt: {{ .Values.jamfpro.customdomain.crt }}
  tls.key: {{ .Values.jamfpro.customdomain.key }}
{{- end -}}
