{{- if .Release.IsInstall -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    dqservice: hostednextcloud
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app: {{ template "nextcloud.fullname" . }}
      cust: "{{ .Values.custnr }}"
      instanceid: "{{ .Values.instanceid }}"
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
  minAvailable: {{ .Values.pdbMinAvailable }}
{{- end -}}
