kind: Service
apiVersion: v1
metadata:
  name: {{ template "jamfpro.fullname" . }}-mysql-srv
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: jamfmysql
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "jamfpro.fullname" . }}-jamfwebapp-srv
  namespace: {{ .Release.Namespace }}
  labels:
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    instanceid: "{{ .Values.instanceid }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: jamfwebapp
    dqservice: hostedjamf
    cust: "{{ .Values.custnr }}"
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8006
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 100
