version: '2'
services:
  manager:
    image: fabianhartmann/mm-reposado:develop
    environment:
      VIRTUAL_HOST: masus.${baseurl}
    stdin_open: true
    volumes:
    - /srv/MMServiceData/MM-REPOSADO:/srv/MMServiceData/MM-REPOSADO
    tty: true
    labels:
      io.rancher.container.pull_image: always
      addtolb: 'true'
  asus:
    image: fabianhartmann/mm-reposado:develop
    environment:
      VIRTUAL_HOST: asus.${baseurl}
    stdin_open: true
    volumes:
    - /srv/MMServiceData/MM-REPOSADO:/srv/MMServiceData/MM-REPOSADO
    tty: true
    labels:
      io.rancher.container.pull_image: always
      addtolb: 'true'
